for the anyall purescript, user-supplied Markings are working
commit e158c5be5aefd9fd091f46773a9099681a63e19e
Author: Meng Weng Wong <mengwong@gmail.com>
Date:   Wed Sep 15 14:55:24 2021 +0800

    updated documentation

commit f9fb13e3a57574768fc98e60083aa1185dbbf507
Author: Meng Weng Wong <mengwong@gmail.com>
Date:   Wed Sep 15 14:49:21 2021 +0800

    believed to be working

commit ec2b73950fc78a418d10c5e9180e391f557bd27e
Author: Meng Weng Wong <mengwong@gmail.com>
Date:   Wed Sep 15 13:45:19 2021 +0800

    why does this not work, lol

        * external marking read into Purescript
        Two {
          value0: Three {
    	value0: Leaf {},
    	value1: 'accelerate',
    	value2: Left { value0: [Just] },
    	value3: Leaf {},
    	value4: 'imbibe',
    	value5: Left { value0: [Just] },
    	value6: Leaf {}
          },
          value1: 'ingest',
          value2: Left { value0: Just { value0: true } },
          value3: Two {
    	value0: Leaf {},
    	value1: 'perambulate',
    	value2: Left { value0: [Just] },
    	value3: Leaf {}
          }
        }
        * now we call paint()
        /Users/mengwong/src/smucclaw/dsl/lib/purescript/ps-anyall/dist/anyall.js:4109
    	throw new Error(msg);
    	^

        Error: error in decodeMarking(NonEmptyList (NonEmpty (TypeMismatch "object" "string") Nil))
    	at exports._crashWith (/Users/mengwong/src/smucclaw/dsl/lib/purescript/ps-anyall/dist/anyall.js:4109:11)
    	at /Users/mengwong/src/smucclaw/dsl/lib/purescript/ps-anyall/dist/anyall.js:4133:37
    	at exports._unsafePartial (/Users/mengwong/src/smucclaw/dsl/lib/purescript/ps-anyall/dist/anyall.js:4100:12)
    	at Object.unsafeCrashWith (/Users/mengwong/src/smucclaw/dsl/lib/purescript/ps-anyall/dist/anyall.js:4132:14)
    	at /Users/mengwong/src/smucclaw/dsl/lib/purescript/ps-anyall/dist/anyall.js:4200:33
    	at /Users/mengwong/src/smucclaw/dsl/lib/purescript/ps-anyall/dist/anyall.js:202:26
    	at decodeMarking (/Users/mengwong/src/smucclaw/dsl/lib/purescript/ps-anyall/dist/anyall.js:4203:9)
    	at /Users/mengwong/src/smucclaw/dsl/lib/purescript/ps-anyall/dist/anyall.js:4215:27
    	at Object.<anonymous> (/Users/mengwong/src/smucclaw/dsl/lib/purescript/ps-anyall/dist/js-to-ps.js:53:63)
    	at Module._compile (node:internal/modules/cjs/loader:1101:14)

commit 5773b8e78aedb726a0515b730577bbe2fc2c8e0b
Author: Meng Weng Wong <mengwong@gmail.com>
Date:   Wed Sep 15 13:26:47 2021 +0800

    paint() is now returning better, just need to fix the parsing

commit 6cbf8c677f92eb7c65ab0bf55d204c235baa1005
Author: Meng Weng Wong <mengwong@gmail.com>
Date:   Wed Sep 15 12:46:58 2021 +0800

    WIP continues

commit fffb713b1dc3b128608c09635b2645d13d60ff4a
Author: Wong Meng Weng <mwwong@smu.edu.sg>
Date:   Wed Sep 15 01:23:52 2021 +0800

    almost, but not quite, working